# Server
server:
  port: 8080

spring:
  application:
    name: CurrencyMateTgBot
  main:
    banner-mode: console
    lazy-initialization: true
  profiles:
    default: dev
  jackson:
    time-zone: ${APP_TIME_ZONE:UTC}

# Feign (Spring Cloud)
feign:
  client:
    config:
      default:
        logger-level: FULL
        connect-timeout: 5000 # ms
        read-timeout: 15000 # ms

# Logging
logging:
  level:
    root: INFO
    dev.sgd.currencymate: INFO
    org.springframework: INFO
    feign.client: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
# Resilience4j (Circuit Breaker)
resilience4j:
  circuitbreaker:
    instances:
      default:
        sliding-window-size: 100
        failure-rate-threshold: 50 # %
        wait-duration-in-open-state: 30000 # ms
        slow-call-rate-threshold: 50 # %
        slow-call-duration-threshold: 3000 # ms
  retry:
    instances:
      default:
        max-attempts: 3
        wait-duration: 2000 # ms
# Actuator
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled:
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true

# Springdoc OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

bot:
  username: ${CURRENCY_MATE_TG_BOT_USERNAME:original_currency_mate_bot}
  token: ${CURRENCY_MATE_TG_BOT_TOKEN:token}

app:
  adapter:
    currencymate:
      url: ${CURRENCYMATE_URL:http://34.30.144.246:80}
      connectTimeoutMs: ${CURRENCYMATE_CONNECT_TIMEOUT_MS:10000} # ms
      readTimeoutMs: ${CURRENCYMATE_READ_TIMEOUT_MS:30000} # ms